name: Daily Free Fire Likes

on:
  schedule:
    # Run at 5:00 AM Indian time (UTC+5:30) which is 11:30 PM UTC
    - cron: '30 23 * * *'
  workflow_dispatch:  # This allows manual triggering if needed

jobs:
  send-likes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz beautifulsoup4
        
    - name: Run Like Sender and Generate Logs
      run: |
        python .github/scripts/send_likes.py
        
    - name: Update logs page
      run: |
        python .github/scripts/update_logs.py
        
    - name: Commit and push if logs changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add logs.html
        git diff --quiet && git diff --staged --quiet || git commit -m "Update logs with latest run data [skip ci]"
        git push
