name: Daily Free Fire Likes

on:
  schedule:
    # Run at 5:00 AM Indian time (UTC+5:30) which is 11:30 PM UTC
    - cron: '30 23 * * *'
  workflow_dispatch:  # This allows manual triggering if needed

jobs:
  send-likes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Run Like Sender
      run: |
        python .github/scripts/send_likes.py
