name: Token Updater

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Debug Information
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "PAT_TOKEN available: ${{ secrets.PAT_TOKEN != '' }}"
        echo "ACCOUNTS_JSON available: ${{ secrets.ACCOUNTS_JSON != '' }}"
        git config --list
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update JWT tokens
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        python .github/scripts/update_tokens.py
        
    - name: Commit and push changes
      run: |
        # Configure git
        git config --global user.name 'RahulExe69'
        git config --global user.email 'actions@github.com'
        
        # Debug token file
        echo "Token file exists: $(test -f token_ind.json && echo 'Yes' || echo 'No')"
        
        # Add and commit only the token file
        git add token_ind.json
        
        # Debug git status
        git status
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update JWT tokens [skip ci]"
          
          # Use explicit URL with PAT_TOKEN
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          
          # Debug remote URL (with token redacted)
          git remote -v | sed 's/https:\/\/.*@/https:\/\/***@/'
          
          # Push with verbose output
          git push -v
          
          echo "Successfully pushed token updates"
        fi
