name: Token Updater

on:
  schedule:
    # Run at 4:30 AM Indian time (UTC+5:30) which is 11:00 PM UTC
    - cron: '0 23 * * *'
  workflow_dispatch:  # For manual triggering

permissions:
  contents: write

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update JWT tokens
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        python .github/scripts/update_tokens.py
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add the token file
        git add token_ind.json
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Commit changes
          git commit -m "Update JWT tokens [skip ci]"
          
          # Push using the PAT_TOKEN
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/RahulExe69/7xLike.git
          git push
          
          echo "Successfully pushed token updates"
        fi
