name: Token Updater

on:
  schedule:
    # Run at 4:30 AM Indian time (UTC+5:30) which is 11:00 PM UTC
    - cron: '0 23 * * *'
  workflow_dispatch:  # For manual triggering

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Explicitly use PAT_TOKEN for checkout
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update JWT tokens
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        python .github/scripts/update_tokens.py
        
    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Configure git
        git config --global user.name 'RahulExe69'
        git config --global user.email 'actions@github.com'
        
        # Add and commit only the token file
        git add token_ind.json
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update JWT tokens [skip ci]"
          
          # Use PAT_TOKEN explicitly for push
          git remote set-url origin https://${PAT_TOKEN}@github.com/RahulExe69/7xLike.git
          git push
          
          echo "Successfully pushed token updates"
        fi
