name: Daily Token Update

on:
  schedule:
    # Run at 4:30 AM Indian time (UTC+5:30) which is 11:00 PM UTC
    - cron: '0 23 * * *'
  workflow_dispatch:  # For manual triggering

permissions:
  contents: write

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to avoid conflicts
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update JWT tokens
      run: |
        python .github/scripts/update_tokens.py
        
    - name: Commit and push if tokens changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Pull latest changes before attempting to push
        git pull --rebase origin main
        
        git add token_ind.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update JWT tokens [skip ci]" && git push)
