name: Daily Token Update

on:
  schedule:
    # Run at 4:30 AM Indian time (UTC+5:30) which is 11:00 PM UTC
    - cron: '0 23 * * *'
  workflow_dispatch:  # For manual triggering

# This is crucial - explicitly declare permissions
permissions:
  contents: write

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # If you have a PAT_TOKEN secret, use it, otherwise use GITHUB_TOKEN
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update JWT tokens
      env:
        # Pass credentials securely through environment variable if defined
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        python .github/scripts/update_tokens.py
        
    - name: Commit and push changes
      # This script handles everything with basic git commands
      run: |
        # Configure git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Stage only the token file
        git add token_ind.json
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit changes with a skip CI message
        git commit -m "Update JWT tokens [skip ci]"
        
        # Push changes
        git push
