name: Daily Token Update

on:
  schedule:
    # Run at 4:30 AM Indian time (UTC+5:30) which is 11:00 PM UTC
    - cron: '0 23 * * *'
  workflow_dispatch:  # For manual triggering

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Update JWT tokens
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: |
        python .github/scripts/update_tokens.py

    - name: Push changes directly to GitHub API
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          
          // Read the updated token file
          const tokenContent = fs.readFileSync('token_ind.json', 'utf8');
          
          // Get the current file to get its SHA
          try {
            const { data: currentFile } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'token_ind.json',
            });
            
            // Update the file through the GitHub API
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'token_ind.json',
              message: 'Update JWT tokens [skip ci]',
              content: Buffer.from(tokenContent).toString('base64'),
              sha: currentFile.sha,
              committer: {
                name: 'GitHub Actions Bot',
                email: 'actions@github.com'
              }
            });
            
            console.log('Successfully updated token_ind.json through GitHub API');
          } catch (error) {
            console.error('Error updating file:', error);
            process.exit(1);
          }
